
development:
  adapter: postgresql
  encoding: unicode
  database: luckypots_ror_development
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: luckypots_ror_test
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: luckypots_ror_production
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
